name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

env:
 GOPRIVATE: github.com/robsonpeixoto/algorithms

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true
          skip-cache: true

      - name: Check if go.sum is updated
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
